project_id = "mzgdlwkmbtzlfuylezhz"

[functions.admin-login]
verify_jwt = false

[functions.admin-chat]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.social-password-reset]
verify_jwt = false

[functions.admin-credentials-update]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.admin-audit]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.generate-event-image]
verify_jwt = false

[functions.send-live-notification]
verify_jwt = false
